server:
  port: 8531
spring:
  application:
    name: file-service
  datasource:
    url: jdbc:mysql://localhost:3306/spacebox?useSSL=false
    username: root
    password: 123456789
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
service:
  auth:
    host: http://localhost:7531/
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000
logging:
  level:
    org:
      hibernate:
        type: trace
#logging:
#  level:
#    ROOT: DEBUG
#        spring.application.name=
#        server.port=9100
#        eureka.client.service-url.default-zone=http://localhost:8761/eureka